name: Compilar Symove

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # IMPORTANTE: Para Windows Forms DEBE ser windows-latest, no ubuntu
    runs-on: windows-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar y generar un solo .exe (Publish)
      # Esto crea la versión final (Release) para Windows 64-bits en un solo archivo
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./salida_compilada

    - name: Subir el ejecutable a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: Symove-Programa
        path: ./salida_compilada/Symove.exe
