name: Compilar y Publicar Symove

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    # Necesitamos permisos para crear el lanzamiento y subir archivos
    permissions:
      contents: write

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar (Publish)
      # Nota: Si quieres que pese menos, cambia self-contained a false
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./salida_compilada

    - name: Crear Tag y Lanzamiento
      uses: softprops/action-gh-release@v1
      with:
        # Esto usa la fecha y el hash del commit como nombre de versión único
        tag_name: v1.0.${{ github.run_number }}
        name: Symove Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: ./salida_compilada/Symove.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
